import type { AnalysisData } from "./types";

export const mockAnalysisData: AnalysisData = {
  _id: "68e5631fc4c47f6c45a399d6",
  customer_name: "Infosys",
  lead_id: "LEAD-XQZ4TVHI",
  balanceSheet: {
    flexibleGroupItems: [],
    fileGroup: "BALANCE_SHEET",
    sourceFiles: ["file-FP6FRrcZaXFNhbs34BYUDs", "file-T1jTyV1ri5UiuvRhobqmf5"],
    totalAssets: {
      value_2025: 5917.31,
      value_2024: 5193.49,
      value_2023: 4555.51,
      source: "bs",
      unit: "₹ Crore",
      fieldName: "TOTAL ASSETS",
    },
    totalEquityAndLiabilities: {
      value_2025: 5917.31,
      value_2024: 5193.49,
      value_2023: 4555.51,
      source: "bs",
      unit: "₹ Crore",
      fieldName: "TOTAL EQUITY AND LIABILITIES",
    },
    nonCurrentAssets: {
      total: {
        value_2025: 1152.2,
        value_2024: 1947.65,
        value_2023: 1530.4,
        source: "bs",
        unit: "₹ Crore",
        fieldName: "Total Non-Current Assets",
      },
      propertyPlantAndEquipment: {
        value_2025: 133.61,
        value_2024: 147.19,
        value_2023: 130.23,
        source: "bs",
        unit: "₹ Crore",
        fieldName: "Property, Plant and Equipment",
      },
      rightOfUseAssets: {
        value_2025: 195.91,
        value_2024: 71.09,
        value_2023: 99.16,
        source: "bs",
        unit: "₹ Crore",
        fieldName: "Right-of-Use Assets",
      },
      capitalWorkInProgress: {
        value_2025: 18.08,
        value_2024: 10.11,
        value_2023: 3.66,
        source: "bs",
        unit: "₹ Crore",
        fieldName: "Capital Work-in-Progress",
      },
      goodwill: {
        value_2025: null,
        value_2024: null,
        value_2023: null,
        source: "bs",
        unit: "₹ Crore",
        fieldName: "Not Found",
      },
      financialAssetsInvestments: {
        value_2025: null,
        value_2024: null,
        value_2023: null,
        source: "bs",
        unit: "₹ Crore",
        fieldName: "Not Found",
      },
      financialAssetsLoans: {
        value_2025: null,
        value_2024: null,
        value_2023: null,
        source: "bs",
        unit: "₹ Crore",
        fieldName: "Not Found",
      },
      otherFinancialAssets: {
        value_2025: 754.66,
        value_2024: 1656.52,
        value_2023: 1222.07,
        source: "bs",
        unit: "₹ Crore",
        fieldName: "Other Financial Assets",
      },
      deferredTaxAssetsNet: {
        value_2025: 14.96,
        value_2024: 15.85,
        value_2023: 16.93,
        source: "bs",
        unit: "₹ Crore",
        fieldName: "Deferred Tax Assets (net)",
      },
      incomeTaxAssetsNet: {
        value_2025: 24.67,
        value_2024: 39.22,
        value_2023: 49.28,
        source: "bs",
        unit: "₹ Crore",
        fieldName: "Non-Current Tax Assets (net)",
      },
      otherNonCurrentAssets: {
        value_2025: 3.85,
        value_2024: 1.01,
        value_2023: 1.55,
        source: "bs",
        unit: "₹ Crore",
        fieldName: "Other Non-Current Assets",
      },
      intangibleAssets: {
        value_2025: 6.46,
        value_2024: 6.66,
        value_2023: 7.52,
        source: "bs",
        unit: "₹ Crore",
        fieldName: "Intangible Assets",
      },
      flexibleGroupItems: [],
    },
    currentAssets: {
      total: {
        value_2025: 4765.11,
        value_2024: 3245.84,
        value_2023: 3025.11,
        source: "bs",
        unit: "₹ Crore",
        fieldName: "Total Current Assets",
      },
      financialAssetsInvestments: {
        value_2025: null,
        value_2024: null,
        value_2023: null,
        source: "bs",
        unit: "₹ Crore",
        fieldName: "Not Found",
      },
      tradeReceivables: {
        value_2025: 380.23,
        value_2024: 319.11,
        value_2023: 318.8,
        source: "bs",
        unit: "₹ Crore",
        fieldName: "Trade Receivables",
      },
      cashAndCashEquivalents: {
        value_2025: 560.59,
        value_2024: 291.74,
        value_2023: 239.67,
        source: "bs",
        unit: "₹ Crore",
        fieldName: "Cash and Cash Equivalents",
      },
      financialAssetsLoans: {
        value_2025: null,
        value_2024: null,
        value_2023: null,
        source: "bs",
        unit: "₹ Crore",
        fieldName: "Not Found",
      },
      otherFinancialAssets: {
        value_2025: 1781.83,
        value_2024: 94.56,
        value_2023: 68.63,
        source: "bs",
        unit: "₹ Crore",
        fieldName: "Other Financial Assets",
      },
      incomeTaxAssetsNet: {
        value_2025: null,
        value_2024: null,
        value_2023: null,
        source: "bs",
        unit: "₹ Crore",
        fieldName: "Not Found",
      },
      otherCurrentAssets: {
        value_2025: 69.57,
        value_2024: 78.1,
        value_2023: 51.77,
        source: "bs",
        unit: "₹ Crore",
        fieldName: "Other Current Assets",
      },
      flexibleGroupItems: [
        {
          fieldName: "Bank Balances other than Cash and Cash Equivalents",
          value_2025: 1067.33,
          value_2024: 1842.75,
          value_2023: 1697.39,
          source: "bs",
          unit: "₹ Crore",
        },
        {
          fieldName: "Asset held for sale",
          value_2025: 23.52,
          value_2024: null,
          value_2023: null,
          source: "bs",
          unit: "₹ Crore",
        },
      ],
    },
    equityAndLiabilities: {
      totalEquity: {
        value_2025: 4233.15,
        value_2024: 3698.89,
        value_2023: 3188.54,
        source: "bs",
        unit: "₹ Crore",
        fieldName: "Total Equity",
      },
      equityShareCapital: {
        value_2025: 21.25,
        value_2024: 21.25,
        value_2023: 21.25,
        source: "bs",
        unit: "₹ Crore",
        fieldName: "Equity Share Capital",
      },
      otherEquity: {
        value_2025: 4211.9,
        value_2024: 3677.64,
        value_2023: 3167.29,
        source: "bs",
        unit: "₹ Crore",
        fieldName: "Other Equity",
      },
      nonCurrentLiabilities: {
        total: {
          value_2025: 276.97,
          value_2024: 151.88,
          value_2023: 160.95,
          source: "bs",
          unit: "₹ Crore",
          fieldName: "Total Non-Current Liabilities",
        },
        financialLiabilitiesBorrowings: {
          value_2025: null,
          value_2024: null,
          value_2023: null,
          source: "bs",
          unit: "₹ Crore",
          fieldName: "Not Found",
        },
        financialLiabilitiesLease: {
          value_2025: 157.75,
          value_2024: 36.76,
          value_2023: 67.49,
          source: "bs",
          unit: "₹ Crore",
          fieldName: "Lease Liabilities",
        },
        otherFinancialLiabilities: {
          value_2025: null,
          value_2024: null,
          value_2023: null,
          source: "bs",
          unit: "₹ Crore",
          fieldName: "Not Found",
        },
        deferredTaxLiabilitiesNet: {
          value_2025: null,
          value_2024: null,
          value_2023: null,
          source: "bs",
          unit: "₹ Crore",
          fieldName: "Not Found",
        },
        otherNonCurrentLiabilities: {
          value_2025: null,
          value_2024: null,
          value_2023: null,
          source: "bs",
          unit: "₹ Crore",
          fieldName: "Not Found",
        },
        flexibleGroupItems: [],
      },
      currentLiabilities: {
        total: {
          value_2025: 1407.19,
          value_2024: 1342.72,
          value_2023: 1206.02,
          source: "bs",
          unit: "₹ Crore",
          fieldName: "Total Current Liabilities",
        },
        financialLiabilitiesBorrowings: {
          value_2025: null,
          value_2024: null,
          value_2023: null,
          source: "bs",
          unit: "₹ Crore",
          fieldName: "Not Found",
        },
        financialLiabilitiesLease: {
          value_2025: 38.92,
          value_2024: 46.47,
          value_2023: 45.68,
          source: "bs",
          unit: "₹ Crore",
          fieldName: "Lease Liabilities",
        },
        tradePayablesMicroAndSmall: {
          value_2025: 30.65,
          value_2024: 41.11,
          value_2023: 24.57,
          source: "bs",
          unit: "₹ Crore",
          fieldName:
            "Total outstanding dues of Micro enterprises and Small enterprises",
        },
        tradePayablesOtherCreditors: {
          value_2025: 1027.21,
          value_2024: 961.58,
          value_2023: 867.42,
          source: "bs",
          unit: "₹ Crore",
          fieldName:
            "Total outstanding dues of creditors other than Micro enterprises and Small enterprises",
        },
        otherFinancialLiabilities: {
          value_2025: 80.87,
          value_2024: 74.85,
          value_2023: 77.99,
          source: "bs",
          unit: "₹ Crore",
          fieldName: "Other Financial Liabilities",
        },
        otherCurrentLiabilities: {
          value_2025: 41.88,
          value_2024: 38.26,
          value_2023: 53.63,
          source: "bs",
          unit: "₹ Crore",
          fieldName: "Other Current Liabilities",
        },
        provisionsCurrent: {
          value_2025: 168.01,
          value_2024: 168.99,
          value_2023: 126.19,
          source: "bs",
          unit: "₹ Crore",
          fieldName: "Provisions",
        },
        incomeTaxLiabilitiesNet: {
          value_2025: 19.65,
          value_2024: 11.46,
          value_2023: 10.54,
          source: "bs",
          unit: "₹ Crore",
          fieldName: "Current Tax Liabilities (net)",
        },
        flexibleGroupItems: [],
      },
      flexibleGroupItems: [],
    },
  },
  profitLoss: {
    fileGroup: "PROFIT_AND_LOSS",
    sourceFiles: [
      "file-6fFj99FVV83oj3x6Q5mc74",
      "file-2NHSL8XqbaeVvCPvfe6vbb",
      "PL_2024_25.pdf",
      "PL_2023_24.pdf",
    ],
    totalIncome: {
      value_2025: 6684.73,
      value_2024: 6097.18,
      value_2023: 5502.88,
      source: "pl",
      unit: "₹ Crore",
      fieldName: "Total Income",
    },
    revenueFromOperations: {
      value_2025: 6409.15,
      value_2024: 5848.91,
      value_2023: 5348.73,
      source: "pl",
      unit: "₹ Crore",
      fieldName: "Revenue from Operations",
    },
    otherIncomeNet: {
      value_2025: 275.58,
      value_2024: 248.27,
      value_2023: 154.15,
      source: "pl",
      unit: "₹ Crore",
      fieldName: "Other Income",
    },
    coreOperatingCosts: {
      value_2025: null,
      value_2024: null,
      value_2023: null,
      source: "pl",
      unit: "₹ Crore",
      fieldName: "Not Found",
    },
    exceptionalItemsNet: {
      value_2025: null,
      value_2024: null,
      value_2023: null,
      source: "pl",
      unit: "₹ Crore",
      fieldName: "Not Found",
    },
    totalExpenses: {
      value_2025: 4797.78,
      value_2024: 4479.43,
      value_2023: 4229.06,
      source: "pl",
      unit: "₹ Crore",
      fieldName: "Total Expenses",
    },
    employeeBenefitExpenses: {
      value_2025: 587.54,
      value_2024: 576.58,
      value_2023: 563.59,
      source: "pl",
      unit: "₹ Crore",
      fieldName: "Employee Benefts Expense",
    },
    depreciationAndAmortizationExpenses: {
      value_2025: 71.8,
      value_2024: 71.17,
      value_2023: 69.97,
      source: "pl",
      unit: "₹ Crore",
      fieldName: "Depreciation and Amortisation Expense",
    },
    financeCost: {
      value_2025: 11.43,
      value_2024: 12.45,
      value_2023: 15.99,
      source: "pl",
      unit: "₹ Crore",
      fieldName: "Finance Costs",
    },
    costOfTechnicalSubContractors: {
      value_2025: null,
      value_2024: null,
      value_2023: null,
      source: "pl",
      unit: "₹ Crore",
      fieldName: "Not Found",
    },
    travelExpenses: {
      value_2025: null,
      value_2024: null,
      value_2023: null,
      source: "pl",
      unit: "₹ Crore",
      fieldName: "Not Found",
    },
    communicationExpenses: {
      value_2025: null,
      value_2024: null,
      value_2023: null,
      source: "pl",
      unit: "₹ Crore",
      fieldName: "Not Found",
    },
    consultancyAndProfessionalCharges: {
      value_2025: null,
      value_2024: null,
      value_2023: null,
      source: "pl",
      unit: "₹ Crore",
      fieldName: "Not Found",
    },
    otherExpensesAggregated: {
      value_2025: 630.23,
      value_2024: 598.62,
      value_2023: 604.45,
      source: "pl",
      unit: "₹ Crore",
      fieldName: "Other Expenses",
    },
    profitBeforeTax: {
      value_2025: 1886.95,
      value_2024: 1617.75,
      value_2023: 1273.82,
      source: "pl",
      unit: "₹ Crore",
      fieldName: "PROFIT BEFORE TAX",
    },
    profitForTheYear: {
      value_2025: 1414.44,
      value_2024: 1201.22,
      value_2023: 949.41,
      source: "pl",
      unit: "₹ Crore",
      fieldName: "PROFIT FOR THE YEAR",
    },
    currentTax: {
      value_2025: 477.99,
      value_2024: 415.43,
      value_2023: 329.41,
      source: "pl",
      unit: "₹ Crore",
      fieldName: "Tax Expense",
    },
    deferredTax: {
      value_2025: 2.72,
      value_2024: 1.07,
      value_2023: "(1.19)",
      source: "pl",
      unit: "₹ Crore",
      fieldName: "Deferred Tax - charge",
    },
    totalComprehensiveIncomeForTheYear: {
      value_2025: 1409.02,
      value_2024: 1201.24,
      value_2023: 953.03,
      source: "pl",
      unit: "₹ Crore",
      fieldName: "TOTAL COMPREHENSIVE INCOME FOR THE YEAR, NET OF TAX",
    },
    earningsPerShare: {
      basic: {
        value_2025: 665.62,
        value_2024: 565.28,
        value_2023: 446.78,
        source: "pl",
        unit: "per share ₹ Crore",
        fieldName: "Basic and Diluted - ` (Face value of `10 each)",
      },
      diluted: {
        value_2025: 665.62,
        value_2024: 565.28,
        value_2023: 446.78,
        source: "pl",
        unit: "per share ₹ Crore",
        fieldName: "Basic and Diluted - ` (Face value of `10 each)",
      },
    },
    flexibleGroupItems: [],
  },
  cashFlow: {
    fileGroup: "CASH_FLOW",
    sourceFiles: [
      "file-GjHRzZW8yVhaAYPPEu4yAV",
      "file-FjkiUm5rK7Cj1x7ZQvRGnP",
      "CF_2024_25.pdf",
      "CF_2023_24.pdf",
    ],
    netCashGeneratedByOperatingActivities: {
      value_2025: 1011.84,
      value_2024: 1212.81,
      value_2023: 893.39,
      source: "cf",
      unit: "₹ Crore",
      fieldName: "Net cash flow from Operating Activities",
    },
    netCashUsedInInvestingActivities: {
      value_2025: 182.18,
      value_2024: -416.03,
      value_2023: -147.71,
      source: "cf",
      unit: "₹ Crore",
      fieldName: "Net cash flow from Investing Activities",
    },
    netCashUsedInFinancingActivities: {
      value_2025: -925.17,
      value_2024: -744.71,
      value_2023: -638.72,
      source: "cf",
      unit: "₹ Crore",
      fieldName: "Net cash flow from Financing Activities",
    },
    cashGeneratedFromOperations: {
      value_2025: 1458.9,
      value_2024: 1617.28,
      value_2023: 1234.25,
      source: "cf",
      unit: "₹ Crore",
      fieldName: "Cash generated from operations",
    },
    profitForTheYear: {
      value_2025: 1886.95,
      value_2024: 1617.75,
      value_2023: 1273.82,
      source: "cf",
      unit: "₹ Crore",
      fieldName: "Profit/(Loss) for the Year",
    },
    incomeTaxesPaid: {
      value_2025: -447.06,
      value_2024: -404.47,
      value_2023: -340.86,
      source: "cf",
      unit: "₹ Crore",
      fieldName: "Income taxes paid",
    },
    adjustmentsToReconcileNetProfitToNetCashProvidedByOperatingActivities: {
      depreciationAndAmortization: {
        value_2025: 71.8,
        value_2024: 71.17,
        value_2023: 69.97,
        source: "cf",
        unit: "₹ Crore",
        fieldName: "Depreciation and Amortization",
      },
      incomeTaxExpense: {
        value_2025: null,
        value_2024: null,
        value_2023: null,
        source: "cf",
        unit: "₹ Crore",
        fieldName: "Income Tax Expense",
      },
      impairmentLossRecognizedReversed: {
        value_2025: null,
        value_2024: null,
        value_2023: null,
        source: "cf",
        unit: "₹ Crore",
        fieldName: "Impairment loss recognized/(reversed)",
      },
      financeCost: {
        value_2025: 11.43,
        value_2024: 12.45,
        value_2023: 15.99,
        source: "cf",
        unit: "₹ Crore",
        fieldName: "Finance Cost",
      },
      interestAndDividendIncome: {
        value_2025: -258.1,
        value_2024: -224,
        value_2023: -142.31,
        source: "cf",
        unit: "₹ Crore",
        fieldName: "Interest and dividend income",
      },
      stockCompensationExpense: {
        value_2025: 12.31,
        value_2024: 14.07,
        value_2023: 12.22,
        source: "cf",
        unit: "₹ Crore",
        fieldName: "Stock compensation expense",
      },
      otherAdjustments: {
        value_2025: null,
        value_2024: null,
        value_2023: null,
        source: "cf",
        unit: "₹ Crore",
        fieldName: "Other adjustments",
      },
      flexibleGroupItems: [],
    },
    changesInAssetsAndLiabilities: {
      tradeReceivablesAndUnbilledRevenue: {
        value_2025: -63.16,
        value_2024: -1.68,
        value_2023: -28.73,
        source: "cf",
        unit: "₹ Crore",
        fieldName: "Trade Receivables and Unbilled Revenue",
      },
      loansOtherFinancialAssetsAndOtherAssets: {
        value_2025: 15.02,
        value_2024: -8.84,
        value_2023: 16.95,
        source: "cf",
        unit: "₹ Crore",
        fieldName: "Loans, Other Financial Assets and Other Assets",
      },
      tradePayables: {
        value_2025: 40.53,
        value_2024: 95.95,
        value_2023: -1.41,
        source: "cf",
        unit: "₹ Crore",
        fieldName: "Trade Payables",
      },
      otherFinancialLiabilitiesOtherLiabilitiesAndProvisions: {
        value_2025: 6.66,
        value_2024: 14.69,
        value_2023: -2.65,
        source: "cf",
        unit: "₹ Crore",
        fieldName:
          "Other Financial Liabilities, Other Liabilities and Provisions",
      },
      flexibleGroupItems: [],
    },
    expenditureOnPropertyPlantAndEquipment: {
      value_2025: -52.6,
      value_2024: -48.33,
      value_2023: -34.11,
      source: "cf",
      unit: "₹ Crore",
      fieldName: "Expenditure on property, plant and equipment",
    },
    depositsPlacedWithCorporation: {
      value_2025: -2320.84,
      value_2024: -4271.67,
      value_2023: -4318.26,
      source: "cf",
      unit: "₹ Crore",
      fieldName: "Deposits placed with Corporation",
    },
    redemptionOfDepositsPlacedWithCorporation: {
      value_2025: 3101.67,
      value_2024: 4129.14,
      value_2023: 5238.94,
      source: "cf",
      unit: "₹ Crore",
      fieldName: "Redemption of deposits placed with Corporation",
    },
    interestAndDividendReceived: {
      value_2025: 125.43,
      value_2024: 143.63,
      value_2023: 102.24,
      source: "cf",
      unit: "₹ Crore",
      fieldName: "Interest and dividend received",
    },
    dividendReceivedFromSubsidiary: {
      value_2025: null,
      value_2024: null,
      value_2023: null,
      source: "cf",
      unit: "₹ Crore",
      fieldName: "Dividend received from subsidiary",
    },
    loanGivenToSubsidiaries: {
      value_2025: null,
      value_2024: null,
      value_2023: null,
      source: "cf",
      unit: "₹ Crore",
      fieldName: "Loan given to subsidiaries",
    },
    loanRepaidBySubsidiaries: {
      value_2025: null,
      value_2024: null,
      value_2023: null,
      source: "cf",
      unit: "₹ Crore",
      fieldName: "Loan repaid by subsidiaries",
    },
    investmentInSubsidiaries: {
      value_2025: null,
      value_2024: null,
      value_2023: null,
      source: "cf",
      unit: "₹ Crore",
      fieldName: "Investment in subsidiaries",
    },
    paymentTowardsAcquisitionOfEntities: {
      value_2025: null,
      value_2024: null,
      value_2023: null,
      source: "cf",
      unit: "₹ Crore",
      fieldName: "Payment towards acquisition of entities",
    },
    receiptPaymentTowardsBusinessTransferForEntitiesUnderCommonControl: {
      value_2025: null,
      value_2024: null,
      value_2023: null,
      source: "cf",
      unit: "₹ Crore",
      fieldName:
        "Receipt/Payment towards business transfer for entities under common control",
    },
    receiptPaymentFromEntitiesUnderLiquidation: {
      value_2025: null,
      value_2024: null,
      value_2023: null,
      source: "cf",
      unit: "₹ Crore",
      fieldName: "Receipt/Payment from entities under liquidation",
    },
    otherReceipts: {
      value_2025: null,
      value_2024: null,
      value_2023: null,
      source: "cf",
      unit: "₹ Crore",
      fieldName: "Other receipts",
    },
    paymentsToAcquireInvestments: {
      flexibleGroupItems: [],
    },
    proceedsOnSaleOfInvestments: {
      flexibleGroupItems: [],
    },
    paymentOfLeaseLiabilities: {
      value_2025: null,
      value_2024: null,
      value_2023: -53.87,
      source: "cf",
      unit: "₹ Crore",
      fieldName: "Payment of lease liabilities",
    },
    sharesIssuedOnExerciseOfEmployeeStockOptions: {
      value_2025: null,
      value_2024: null,
      value_2023: null,
      source: "cf",
      unit: "₹ Crore",
      fieldName: "Shares issued on exercise of employee stock options",
    },
    otherPayments: {
      value_2025: null,
      value_2024: null,
      value_2023: null,
      source: "cf",
      unit: "₹ Crore",
      fieldName: "Other payments",
    },
    paymentOfDividends: {
      value_2025: -871.22,
      value_2024: -690.6,
      value_2023: -584.36,
      source: "cf",
      unit: "₹ Crore",
      fieldName: "Payment of dividends",
    },
    netIncreaseDecreaseInCashAndCashEquivalents: {
      value_2025: 268.85,
      value_2024: 52.07,
      value_2023: 106.96,
      source: "cf",
      unit: "₹ Crore",
      fieldName: "Net increase/(decrease) in cash and cash equivalents",
    },
    effectOfExchangeDifferencesOnTranslationOfForeignCurrencyCashAndCashEquivalents:
      {
        value_2025: null,
        value_2024: null,
        value_2023: null,
        source: "cf",
        unit: "₹ Crore",
        fieldName:
          "Effect of exchange differences on translation of foreign currency cash and cash equivalents",
      },
    cashAndCashEquivalentsAtTheBeginningOfTheYear: {
      value_2025: 291.74,
      value_2024: 239.67,
      value_2023: 132.71,
      source: "cf",
      unit: "₹ Crore",
      fieldName: "Cash and cash equivalents at the beginning of the year",
    },
    cashAndCashEquivalentsAtTheEndOfTheYear: {
      value_2025: 560.59,
      value_2024: 291.74,
      value_2023: 239.67,
      source: "cf",
      unit: "₹ Crore",
      fieldName: "Cash and cash equivalents as at the end of the year",
    },
    flexibleGroupItems: [],
  },
  createdAt: "2025-10-07T18:59:43.290Z",
  updatedAt: "2025-10-07T18:59:43.290Z",
  __v: 0,
};
